### ISSUE TITLE
wrap image

### ISSUE THREAD

**Issue by neo125874** [cdvntr/react-native-confetti#10]
hello, any example to implement the readme's gif? 
put the <Image/> inside the <Confetti></Confetti> or something? 

thanks

**Comment by cdvntr** [comment]
@neo125874 hey,

the example was built with [https://github.com/jorilallo/react-native-emoji](url)

Basically;

```
<View style={styles.container}>
  <Text style={{fontSize: 50}}><Emoji name="ghost"/></Text>
  <Confetti ref={(node) => this._confettiView = node}/>
</View>
```

**Comment by neo125874** [comment]
@cdvntr thanks, i love this lib, it works!
