### ISSUE TITLE
stopConfetti doesn't exist

### ISSUE THREAD

**Issue by adambubenicek** [cdvntr/react-native-confetti#6]
I was having issues with using `stopConfetti()` from the docs, it simply didn't exist. Then I realised that the code implementing it doesn't yet exist in my local copy from NPM (0.0.4).

<img width="280" alt="screen shot 2017-05-12 at 10 21 59" src="https://cloud.githubusercontent.com/assets/3390406/25989546/e66d5512-36fc-11e7-9eae-adc048be896f.png">

Would simple bump and publish solve this issue? I'd be happy to help, but not sure if I can.

Thanks for this package, as well as help with this!

**Comment by jeffreymendez1993** [comment]
@adambubenicek  change the function name from stoConfetti to stopConfettiAnimation in the lib and use stopConfettiAnimation and it will work. Im not sure why he named the function the same as the class variable bool LOL.

**Comment by kolyan94** [comment]
@adambubenicek 
you can simply set value true and it'll work.
`this._confettiView.stopConfetti = true;`

**Comment by adambubenicek** [comment]
Thanks guys, created a PR to fix the naming conflict https://github.com/cdvntr/react-native-confetti/pull/11

Slightly off topic topic – initially I think the problem was that NPM version was outdated (didn't have `stopConfetti ` property nor flag). That is now fixed since NPM version is at 0.0.5, although `package.json` still is at 0.0.4

**Comment by cdvntr** [comment]
Hey,

Package.json and npm are both up to date atm.

**Comment by adambubenicek** [comment]
Awesome, thanks @cdvntr !
